### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by Ironholds** [wrathematics/sylcount#1]
Any plans to put this up there?

**Comment by wrathematics** [comment]
I was planning to eventually. I'm interviewing for several positions right now, so that's where most of my attention has been.

**Comment by Ironholds** [comment]
Ahhh that makes sense!

**Comment by wrathematics** [comment]
On CRAN. Package checks are trickling out, so we'll see if there are any surprises. But hopefully everything is fine.

**Comment by Ironholds** [comment]
Yay!
